#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     distanceSensor, sensorSONAR)
#pragma config(Motor,  motorA,          rotationMotor, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     extentionMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftdrive,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightdrive,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     liftMotor,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    verticalArm,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    GPM,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    verticalArm2,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "\\GlobVars.h";
#include "\\GlobFuncs.c";

task main()
{
	/*
	Close GPM.
	Lift arm up to position servo 1 = 250 and servo 2 = 5.
	Spin the turntable 90 deg.
	Extend arm at 40% power for 2 sec.
	Drive forward until the encoder count is x.
	Stop motors.
	Open GPM
	Drive forward until the encoder count is y
	*/
	// these variables serve no purpose other than being placeholders
	int NinetyDegrees = 90;
	int basketDistance = 2500;
	int x = 2; // changeable
	int y = 3; // changeable

	// autonomous



	motor[GPM] = 130;
	servo[verticalArm] = 250;
	servo[verticalArm2] = 5;
	motor[rotationMotor] = NinetyDegrees;
	motor[extentionMotor] = 40;
	wait1Msec(2000);

	while (nMotorEncoder[leftdrive] < x)
	{
		motor[leftdrive] = 75;
		motor[rightdrive] = 75;
	}

	motor[leftdrive] = 0;
	motor[rightdrive] = 0;

	nMotorEncoder[leftdrive] = 0;
	while (nMotorEncoder[leftdrive] < y)
	{
		motor[leftdrive] = 75;
		motor[rightdrive] = 75;
	}

	motor[leftdrive] = 0;
	motor[rightdrive] = 0;


}
